### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by chivalrousAlisa** [dogzhang/Solitaire_Html#1]
在电脑上玩有bug，中间层叠区 展示不了所有的牌，手机上横屏的时候也不行

**Comment by dogzhang** [comment]
这个适用于竖屏，横屏的话，如果屏幕高度不够，就会出现较长的列显示不全
![_20160819181713](https://cloud.githubusercontent.com/assets/12051004/17806787/339691ae-6639-11e6-9aec-51629fc9e2cd.png)
这个是1080P屏幕全屏的截图，基本上是没有问题的
